In [69]:
# Converting "Newspeak House Unmailing List.xlsx" to a database

# "A repository of open channels containing people working on political and civic technology."

# Initial cleaning:
# * download the four individual sheets in the Google Sheet
# * remove the left-most column (present for construction notes)
# * trim any excess rows at the top

# use of colours
    # purple and green - don't know what they mean!

# Groups
# Membership required
# Newsletters
    # "need to expand" snipped off leftmost column "Name":"Awesome newsletters"
    # a load of blank rows in middle
# working
    # quite messy
    # a lot of stuff remaining in leftmost column
    # copy of header column appears pasted into a row


# URL	Name	Type	Self-Description	Purpose	Some Associated Projects	District	Country	Language	Topic	Topic	Topic	Topic	Topic	Notes

In [70]:
## Sanitation

# URL -> check they all work (at least, check that they function *now*!)
   # at the moment, this appears to be the "Primary Field" (unique key)
    # which is a problem, since it's not unique!
# Name -> should be unique (some are not)
    # we have organisations with different entries fro slackchat and github
# Type -> we need a fixed set of types
# Self-Description -> Text
# Purpose -> Text
# Some Associated Projects -> another table
# District -> **very patchy, no clear ontology (I'm sure this already exists)
# Country -> **ditto, no need to remake the wheel (lot of variants on 'global')
# Language -> **English (again, don't remake wheel)
# Topic1 ... Topic5 -> need a finite list
    # multiple select would look good if I can figure out
    # how to import directly or convert? ("gfgf,fgfg,fgf" maybe?)
    # apparently so
# Notes -> emails, links ... and some stuff that looked like Types
    # Network/In Person Event
# Sheet -> higher level type of ... Type

# Reorder columns!
# ['URL', 'Name', 'Type', 'Self-Description', 'Purpose',
#        'Some Associated Projects', 'District', 'Country', 'Language', 'Topic1',
#        'Topic2', 'Topic3', 'Topic4', 'Topic5', 'Notes', 'Sheet']

['URL', 'Name',
 'Sheet', 'Type',
 'Self-Description', 'Purpose',
 'Notes',
 'Topics',
 'Projects',
 'Language', 'Country', 'District' ]

# Extra tables?
# District, Country
    # sure this already exist as a ready made (pair of) tables
# Topics
# Sheet, Type
    # should probably also be a set of paired tables
# Sheet dropped as not adding anything

['URL',
 'Name',
 'Sheet',
 'Type',
 'Self-Description',
 'Purpose',
 'Notes',
 'Topics',
 'Projects',
 'Language',
 'Country',
 'District']

In [71]:
# Newspeak House Unmailing List - working - trimmed
# this sheet was particularly mucky
# I moved the left-hand column "entry notes" into the Notes column
# But there was still a number of entries which contained nothing but names
# Presumably someone was planning on filling them in when they looked them up

# I've snipped those out - here they are in case anyone wants to add them later:

# Open Knowledge Open Access List / Open Science List (big list, not that much activity)
# https://snuproject.wordpress.com/sources/
# http://brigade.codeforamerica.org/brigade/	Code for America													OOD	
# https://representcommunity.herokuapp.com/														404	
# Foianet <foianet@foiadvocates.info>														???

In [72]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline
import pickle, os

In [73]:
SA_data_folder = "../Saperia_archive_data/" # Saperia_archive\Saperia_archive_data
SA_code_folder = "../Saperia_archive_code/"

In [74]:
SA_Groups         = pd.read_csv(SA_data_folder+"Newspeak House Unmailing List - Groups - trimmed.csv")
print("SA_Groups " , SA_Groups.shape)

SA_Membership_req = pd.read_csv(SA_data_folder+"Newspeak House Unmailing List - Membership required - trimmed.csv")
print("SA_Membership_req " , SA_Membership_req.shape)

SA_Newsletters    = pd.read_csv(SA_data_folder+"Newspeak House Unmailing List - Newsletters - trimmed.csv")
print("SA_Newsletters " , SA_Newsletters.shape)

SA_working = pd.read_csv(SA_data_folder+"Newspeak House Unmailing List - working - trimmed.csv")
print("SA_working " , SA_working.shape)

SA_Groups  (120, 15)
SA_Membership_req  (15, 15)
SA_Newsletters  (10, 15)
SA_working  (27, 15)

In [75]:
all(SA_Groups.columns == SA_Membership_req.columns) and all(SA_Membership_req.columns == SA_Newsletters.columns)
# column header identical

True

In [76]:
SA_Groups.columns

Index(['URL', 'Name', 'Type', 'Self-Description', 'Purpose',
       'Some Associated Projects', 'District', 'Country', 'Language', 'Topic',
       'Topic.1', 'Topic.2', 'Topic.3', 'Topic.4', 'Notes'],
      dtype='object')

In [77]:
# Sheet doesn't really add anything not already covered by type

# SA_Groups["Sheet"]         = "Groups"
# SA_Membership_req["Sheet"] = "Membership_req"
# SA_Newsletters["Sheet"]    = "Newsletters"
# # SA_working["Sheet]       = "working"

In [78]:
SA = SA_Groups
SA = SA.append(SA_Membership_req,        ignore_index=True, verify_integrity=True)
SA = SA.append(SA_Newsletters,           ignore_index=True, verify_integrity=True)
SA = SA.append(SA_working,               ignore_index=True, verify_integrity=True)

In [79]:
SA.describe()

,URL,Name,Type,Self-Description,Purpose,Some Associated Projects,District,Country,Language,Topic,Topic.1,Topic.2,Topic.3,Topic.4,Notes
count,172,167,166,153,152,22,44,147,172,160,117,61,17,3,35
unique,169,157,39,141,136,19,23,13,2,55,51,34,12,3,24
top,https://www.facebook.com/groups/1170805349664629/,Data For Democracy,Mailing List,Tech with humankind in mind,Promote the development of human centred projects,http://www.involve.org.uk/,London,UK,English,Journalism,Service Design,Future of Work,Open Data,Internatlonalism,In Person Event
freq,2,3,31,6,7,3,18,91,171,12,12,9,4,1,7

In [80]:
# lets have a look at the distribution of strings in Type, Country, District, Topic variables

In [81]:
# but first lets avoid spurious differences in capitalisation by making these columns lower case
for col in ["Type","Country","District","Topic","Topic.1","Topic.2","Topic.3","Topic.4"]:
    print(col)
    non_null = SA[col].notnull()
    
    SA[col][non_null] =\
        SA[col][non_null].apply(lambda x: x.lower().strip())

Type
Country
District
Topic
Topic.1
Topic.2
Topic.3
Topic.4

In [82]:
SA["Type"].value_counts()

mailing list                 37
meetup group                 32
slack team                   17
membership portal            15
newsletter                    8
forum                         8
facebook group (public)       8
facebook group                6
facebook group (closed)       5
directory                     4
slack channel                 3
github repository             3
google group                  2
user portal                   2
accelerator                   1
podcast                       1
eventbrite page               1
community website             1
events listing                1
etherpad                      1
event page                    1
facebook page                 1
mailing list/newsletter       1
wiki                          1
weekly teleconference         1
visualisation tool            1
google doc                    1
google sheet as directory     1
facebook group (secret)       1
website                       1
Name: Type, dtype: int64

In [83]:
SA["District"].value_counts()

london              18
uk                   3
south east           2
scotland             2
bristol              1
northern ireland     1
dublin               1
online               1
midlands             1
usa                  1
ny                   1
bath                 1
south                1
manchester           1
hackney              1
south west           1
global               1
based in usa         1
cambridge            1
birmingham           1
wales                1
sheffield            1
oxford               1
Name: District, dtype: int64

In [84]:
SA["Country"].value_counts()

uk                         92
usa                        23
international              15
worldwide                   9
eu                          2
uk/usa                      2
global                      1
us                          1
ireland                     1
south & central america     1
Name: Country, dtype: int64

In [85]:
SA[["Topic","Topic.1","Topic.2","Topic.3","Topic.4"]].stack().value_counts()

democracy                              21
technology                             21
open data                              19
journalism                             17
civic tech                             13
service design                         12
education                              12
publishing                             11
government                             11
open government                        10
progressive                             9
unions                                  9
future of work                          9
co-ops                                  9
activism                                8
academia                                7
local government                        7
third sector                            6
transparency                            6
continuing professional development     5
data science                            4
digital democracy                       4
data visualisation                      4
health                                  4
public engagement                       4
ai                                      3
politics                                3
diversity                               3
civic technology                        3
economics                               3
                                       ..
internatlonalism                        1
learn to code                           1
medtech                                 1
uk parliament                           1
announcments                            1
news                                    1
accountability                          1
open society                            1
open technology                         1
open access                             1
community activism                      1
media                                   1
d3.js                                   1
coding for research                     1
foi                                     1
social entrepreneur                     1
investigation                           1
data security                           1
social justice                          1
economy                                 1
sustainability                          1
data journalism                         1
data technology                         1
research                                1
innovation                              1
parliamentary processes                 1
local representation                    1
social enterprise                       1
hackathons                              1
newpolitics                             1
Length: 108, dtype: int64

In [86]:
# pd.DataFrame( SA[["Topic","Topic.1","Topic.2","Topic.3","Topic.4"]].stack().value_counts() )\
#     .to_csv(SA_data_folder+"topics_list.csv")

In [87]:
SA.columns = ['URL', 'Name', 'Type', 'Self-Description', 'Purpose',
       'Projects', 'District', 'Country', 'Language', 'Topic1',
       'Topic2', 'Topic3', 'Topic4', 'Topic5', 'Notes']

In [88]:
#
Topic_replace_dict = {"debt resisitance":"debt resistance",
                      "community org":"community organising",
                      "community":"community organising", # should I include "community activism"
                      "internatlonalism":"internationalism",
                      "announcments":"announcements",
                      "foi":"freedom of information",
                      "newpolitics":"new politics",
                      "accountability":"transparency"
                     }


for topic_column in ['Topic1', 'Topic2', 'Topic3', 'Topic4', 'Topic5']:
    
    for ind in SA[topic_column].index:
        
        el = SA.loc[ind,topic_column]
        if el in Topic_replace_dict.keys():
            SA.loc[ind,topic_column] = Topic_replace_dict[el]
#         print(SA.loc[ind,topic_column])

In [89]:
# things to copy from Types to Notes
notes_dict   = {"facebook group (closed)": "facebook group (closed)"}

# types replace dictionary
Type_replace_dict = {"facebook group (secret)": "facebook group", # covered in notes
                "facebook group (public)": "facebook group", # default
                "facebook group (closed)": "facebook group", # add to notes
                "slack channel":"slack team", # same thing?
                "user portal":"membership portal", # same thing?
                "mailing list/newsletter":"mailing list", # DataKind only example, has both, but looks more mailing list
                "facebook page":"facebook group", # 1 example, technically a page, but looks like they intend. a group!
                "website":"community website", # I think these are all going to be community websites
                "event page":"events listing", # 'events page' is an 'events listing'
                "google sheet as directory":"directory",
                "accelerator":"mailing list",} # example *is* an acc. - but the point of contact is a mailing list

# countries replace dictionary
# eu/us/uk/us/international/ireland/south & central america 
Country_replace_dict = {"International":"international",
                        "Worldwide":"international",
                        "worldwide":"international",
                        "global":"international",
                        "uk/usa":"uk/us"
                        }

# dictionary for overwriting 
District_overwrite_Country_dict = {"london":"uk",
                        "uk":"uk",
                        "scotland":"uk",
                        "south east":"uk", # lazy assumption here that these are districts in UK!
                        "midlands":"uk",
                        "south":"uk",
                        "online":"international", # I guess!
                        "sheffield":"uk",
                        "global":"international",
                        "bath":"uk",
                        "ny":"us",
                        "oxford":"uk",
                        "south west":"uk",
                        "dublin":"ireland",
                        "hackney":"uk", # don't want to throw information away, but feel this should probably be "London"
                        "bristol":"uk",
                        "usa":"us",
                        "birmingham":"uk",
                        "based in usa":"us",
                        "northern ireland":"uk",
                        "wales":"uk",
                        "manchester":"uk",
                        "cambridge":"uk"                                    
                        }

# districts replace dictionary
District_replace_dict = {"uk":np.nan,
                         "online":np.nan,
                         "global":np.nan,
                         "usa":np.nan,
                         "based in usa":np.nan,
                         "hackney":"london"}


                
# Should we separate functional distinction (forum/listing/website) from provider/platform (facebook, eventbrite)
                
# Form of Interaction / Platform for interaction / Thing you are interacting with
                
# e.g. discussion forum / slack / about NESTA?

In [90]:
# updated columns in Type and Notes based on Type value and notes_dict and Type_replace_dict
SA["Notes_updated"] = SA["Notes"]
SA["Type_updated"]  = SA["Type"]

                
for type_value in SA["Type"].value_counts().index:
    
    rows = SA["Type"]==type_value    
    
    # order matters here
    # copy these things into notes dependending on Type value
    if type_value in notes_dict.keys():
        SA["Notes_updated"][rows] = SA["Notes"][rows] + ";" + notes_dict[type_value]

    # overwrite Type depending on Type value
    if type_value in Type_replace_dict.keys():
        SA["Type_updated"][rows]  = Type_replace_dict[type_value]

In [91]:
# update Country based on values in Country column and Country_replace_dict
SA["Country_updated"]   = SA["Country"]

for country_value in SA["Country"].value_counts().index:
    
    rows = SA["Country"]==country_value
    
    if country_value in Country_replace_dict.keys():
        SA["Country_updated"][rows] = Country_replace_dict[country_value]

In [92]:
# update Distrct and Country based on values in District column and
# District_replace_dict and District_overwrite_Country_dict
SA["District_updated"]  = SA["District"]

for district_value in SA["District"].value_counts().index:
    
    rows = SA["District"]==district_value    
    

    # order matters here
    if district_value in District_overwrite_Country_dict.keys():
        SA["Country_updated"][rows] = District_overwrite_Country_dict[district_value]

    if district_value in District_replace_dict.keys():
        SA["District_updated"][rows] = District_replace_dict[district_value]

In [93]:
# sanity check
SA[["Country","Country_updated","District","District_updated"]].drop_duplicates()

,Country,Country_updated,District,District_updated
0,uk,uk,south east,south east
2,global,international,global,NaN
3,uk,uk,london,london
4,uk,uk,NaN,NaN
7,NaN,NaN,NaN,NaN
8,us,us,NaN,NaN
12,uk,uk,hackney,london
14,uk,uk,uk,NaN
15,usa,us,usa,NaN
16,worldwide,international,NaN,NaN
21,usa,us,based in usa,NaN
23,international,international,NaN,NaN
24,usa,usa,NaN,NaN
30,eu,eu,NaN,NaN
59,usa,international,online,NaN
72,uk,uk,sheffield,sheffield
74,uk,uk,bristol,bristol
75,uk,uk,bath,bath
76,uk,ireland,dublin,dublin
77,uk,uk,manchester,manchester
86,uk,uk,northern ireland,northern ireland
87,uk,uk,scotland,scotland
88,uk,uk,wales,wales
91,uk,uk,south west,south west
92,uk,uk,south,south
94,uk,uk,oxford,oxford
100,uk,uk,cambridge,cambridge
109,ireland,ireland,NaN,NaN
110,uk,uk,birmingham,birmingham
114,uk/usa,uk/us,NaN,NaN
125,usa,us,ny,ny
132,uk,uk,midlands,midlands
155,south & central america,south & central america,NaN,NaN

In [94]:
SA[["Type","Type_updated","Notes_updated"]].drop_duplicates()

,Type,Type_updated,Notes_updated
0,mailing list,mailing list,NaN
1,slack team,slack team,NaN
3,meetup group,meetup group,In Person Event
5,forum,forum,NaN
6,facebook group,facebook group,NaN
8,github repository,github repository,NaN
18,mailing list,mailing list,Worldwide in this case is very focused on the ...
19,forum,forum,Completely open list - advocates for encryptio...
20,slack team,slack team,Email r.carbomascarell@gmail.com to get an invite
24,weekly teleconference,weekly teleconference,NaN
27,etherpad,etherpad,NaN
37,facebook group (public),facebook group,NaN
38,forum,forum,email: ogp@dgroups.org to join
45,wiki,wiki,NaN
47,user portal,membership portal,NaN
54,facebook page,facebook group,NaN
59,slack team,slack team,https://www.progcode.org/
60,facebook group (closed),facebook group,NaN
70,facebook group (closed),facebook group,In Person Event;facebook group (closed)
71,community website,community website,NaN
72,event page,events listing,NaN
73,meetup group,meetup group,NaN
85,mailing list,mailing list,Network
90,slack channel,slack team,NaN
93,eventbrite page,eventbrite page,NaN
94,meetup group,meetup group,www.dhox.org.
107,meetup group,meetup group,http://www.opencharityuk.org/
114,github repository,github repository,https://medium.com/data-for-democracy/the-firs...
115,slack team,slack team,https://medium.com/data-for-democracy/the-firs...
116,google group,google group,https://opencorporates.com/
119,google group,google group,NaN
120,membership portal,membership portal,NaN
128,membership portal,membership portal,Network
130,membership portal,membership portal,Newsletter is on http://localgovdigital.info/l...
132,membership portal,membership portal,midlandspeergroup@localgovdigital.info
135,newsletter,newsletter,NaN
138,mailing list/newsletter,mailing list,NaN
144,github repository,github repository,"Pulled out a few obvious ones, wrt political t..."
145,NaN,NaN,formerly markets for good
146,facebook group (secret),facebook group,Need an invite from an existing member or a di...
147,NaN,NaN,NaN
152,website,community website,only contact details are telephone based. no n...
154,mailing list,mailing list,archive - not active
155,directory,directory,"all tools, no discussions"
156,directory,directory,"no discussion, no mailing list; no mailing lis..."
157,visualisation tool,visualisation tool,NaN
158,google sheet as directory,directory,NaN
160,events listing,events listing,NaN
161,podcast,podcast,NaN
163,facebook group (closed),facebook group,little discussion;facebook group (closed)
164,slack team,slack team,?
166,google doc,google doc,NaN
168,mailing list,mailing list,"archive?, not active"
169,directory,directory,NaN
170,directory,directory,NGO?
171,accelerator,mailing list,NaN

In [95]:
# url replacement
# errors:
# http://newsnerdery.org/ Slack -> http://newsnerdery.org/

In [96]:
# NOTES ON LOOKING AT CONTENT

# Need an extra column for "Organisation" to link entries that are all about same organisation with different channels
# or different locations

In [97]:
# SA[["Type","Type_updated","Notes_updated"]]
# SA[["Country","Country_updated","District","District_updated"]].drop_duplicates()
SA["District"] = SA["District_updated"]
SA["Country"]  = SA["Country_updated"]
SA["Notes"]    = SA["Notes_updated"]
SA["Type"]     = SA["Type_updated"]

In [98]:
# Setup for airtable output!

In [99]:
# Merge topics (into comma separated list)
SA["Topics"] = \
    SA[['Topic1','Topic2', 'Topic3', 'Topic4', 'Topic5']]\
    .apply( lambda x: x.str.cat(sep=','), axis=1)

In [100]:
# Drop redundant columns
SA = SA.drop(['Topic1','Topic2', 'Topic3', 'Topic4', 'Topic5'],axis=1)

In [101]:
# reorder columns
SA = SA[ ['URL', 'Name',
 'Type',
 'Self-Description', 'Purpose',
 'Topics',
 'Projects',
 'Language', 'Country', 'District',
 'Notes' ] ]

In [102]:
# maybe we should include the key for now?
SA.to_csv(SA_data_folder+"Newspeak House Unmailing List - processed.csv", index=False, encoding='utf-8')

In [103]:
# Airtable Setup Notes

# * important csv
# * update name "Newspeak House Unmailing List"
#     we're going to have to add version numbering!
#     (or update a single database by updating and overwriting - not sure you can do that!)
# * convert Sheet & Type to Single Select [Sheet dropped]
# * convert Topics to Multiple Select
# * convert Self-Description, Purpose to Long Text
# * convert Country, District, Language to Single Select
# * convert Url to Url type
#     (this is supposed to make it easy to click/launch
#     - but I find it only lets me launch *after* I've opened individual record - which is irritating!)